Отправляю на ревью
Yulia3011/ono-tebe-nado pull request #1
Opened 2024-02-27 16:36 UTC by Yulia3011

2024-02-27 18:00 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- похоже на макет
- нет скролла от 1100px и более и все элементы отображаются корректно
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично»**

- `1, 2, first, second и т.д` - порядковые числительные не следует применять  в названиях, т.к. порядок или числовое значение может измениться. Нужно переименовать все подобные классы




_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - струтуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-02-27 18:00 UTC, Avaakum commented on styles/global.css
> +  background-color: black;
Лишний стиль

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +    inset: 0;
---

**Отлично:**

Корректное выравнивание

2024-02-27 18:00 UTC, Avaakum commented on styles/global.css
> +  width: 1100px;
---

**Можно лучше:**

/*!!!   Вместо ширины можно добавить padding для каждой секции от краёв экрана, чтобы был отступ от краёв экрана при любой ширине секции   

  Если использовать min-width для ширины страницы и подправить вёрстку, где это будет необходимо(что бы при большей ширине экрана контент страницы всегда был по центру), то подобные страницы хорошо растягиваются на любую ширину экрана  */

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +    font-weight: regular;
Некорректное значение свойства. Примеры и варианты значений этого свойства можно посмотреть поискав по названию свойства на

-  https://doka.guide/
-  https://developer.mozilla.org/ru/

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +    <link rel="stylesheet" href="./styles/global.css">
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +      <a class="header__logo-image-link">
---

**Отлично:**

Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)  для улучшения семантики страницы.

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +      <div class="contacts">
Используйте семантический тег ` <address> ` для всей контактной информации

https://doka.guide/html/address/

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +      <div class="contacts-footer">
Используйте семантический тег ` <address> ` для всей контактной информации

https://doka.guide/html/address/

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +        <address class="address">наб. Принсенграхт 263-265, Амстердам</address>
Используйте для текста тег параграф

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +        <address class="address">наб. Принсенграхт 263- 265, Амстердам</address>
Используйте для текста тег параграф

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +        <a href="mailto:info@sobaka.ge">info@sobaka.ge</a><br>
Лишний тег br, следующий тег должен быть параграф (блочный элемент), поэтому он в любом случае займёт следующую строку

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +        <a href="mailto:info@sobaka.ge">info@sobaka.ge</a><br>
Лишний тег br, следующий тег должен быть параграф (блочный элемент), поэтому он в любом случае займёт следующую строку

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +          <span class="accent-span line-hight-115">о<span class="letter-spacing-60">но</span></span>
`1, 2, first, second и т.д` - порядковые числительные не следует применять  в названиях, т.к. порядок или числовое значение может измениться. Используйте описание по смыслу, например text-size-big

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +          <li class="lots__card-list-item">
---

**Отлично:**

Отличная семантика и структура

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +        <div class="about__text">
---

**Можно лучше:**

- Для улучшения семантики этого блока можно использовать тег `<article>` 

 - https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +      <ul class="footer__social-list">
---

**Можно лучше:**

Можно использовать для обертки списка ссылок тег `<nav>`, можно даже без класса, только для семантики.
Этим элементом принято выделять список из ссылок, отвечающий за навигацию по сайту и не только. Добавление этого элемента улучшает восприятие вашей верстки поисковыми машинами, а так же скринридерами. 
Можно использовать несколько тегов `nav` в проекте.

https://doka.guide/html/nav/#alyona-batickaya-sovetuet

2024-02-27 18:00 UTC, Avaakum commented on index.html
> +        <li class="footer__social-list-item"><a class="footer__social-link" href="#0"><img class="footer__social-icon" src="./images/yt.svg" alt="Оно тебе надо"></a></li>
---

**Отлично:**

Отлично, использован список для повторяющихся элементов

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +    display: grid;
---

**Можно лучше:**

/*!!! В header для выравнивания удобно использовать грид. Ячейки по краям будут занимать ширину по одному фрагменту, а логотип только ширину равную минимальной ширине контента (min-content).
  
  А для выравнивания внутри грид-ячейки в таких случаях удобно использовать

- https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
- https://developer.mozilla.org/ru/docs/Web/CSS/align-self*/

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +.lots__look-more-link {
Нужно ограничить максимальную ширину ссылки в соответствии с контентом, значение `fit-content` или изменить выравнивание элемента, чтобы он не занимал больше пространства, чем внутренний контент. Сейчас ссылка занимает всю ширину родителя и может быть нажата в пустом месте.

https://developer.mozilla.org/ru/docs/Web/CSS/max-width

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +    padding-left: 40px;
---

**Можно лучше:**

Нужно заменить padding на margin **для любого разрешения**(если страница с адаптацией), т.к. padding является частью элемента(в данном случае ссылки/кнопки) и на него можно нажать в пустом месте(где его визуально нет)

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +    background-image: url(../images/card-lot-01.jpg);
У карточек меняется только св-во background-image, остальные стили одинаковые. Нужно присвоить их для одного класса .card, чтобы стили не дублировались. И удалить остальные стили кроме background-image для разных классов.

2024-02-27 18:00 UTC, Avaakum commented on styles/style.css
> +    flex-wrap: wrap;
---

**Отлично:**

Новые карточки переходят на следующую строку и занимают всю ширину контейнера

2024-03-04 10:40 UTC, nehydna commented
Юлия, здравствуйте) Вы отлично поработали, спасибо за правки!
Исправлены ошибки в наименовании классов, убраны лишние стили у модификаторов, клик по ссылке нельзя сделать по пустому пространству, все значения свойств корректны. Все отлично, работу принимаю)

2024-03-05 12:35 UTC, merged